# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        loginWindow.setFont(font)
        loginWindow.resize(792, 466)
        loginWindow.setMinimumSize(QtCore.QSize(0, 0))
        loginWindow.setMaximumSize(QtCore.QSize(792, 466))
        self.centralwidget = QtWidgets.QWidget(loginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEdit.setFont(font)
        self.lineEdit.setGeometry(QtCore.QRect(360, 130, 220, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 130, 145, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 160, 145, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 160, 220, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButtonLogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(230, 215, 141, 32))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonRegister = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRegister.setGeometry(QtCore.QRect(230, 250, 331, 32))
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.pushButtonReset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReset.setGeometry(QtCore.QRect(420, 215, 141, 32))
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(460, 190, 86, 20))
        self.checkBox.setObjectName("checkBox")
        loginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(loginWindow)
        self.statusbar.setObjectName("statusbar")
        loginWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(loginWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 792, 24))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        loginWindow.setMenuBar(self.menuBar)
        self.actions = QtWidgets.QAction(loginWindow)
        self.actions.setObjectName("actions")
        self.action = QtWidgets.QAction(loginWindow)
        self.action.setObjectName("action")
        self.actionsd = QtWidgets.QAction(loginWindow)
        self.actionsd.setObjectName("actionsd")
        self.action_2 = QtWidgets.QAction(loginWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action_2)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "欢迎使用Codia——登陆"))
        self.label.setText(_translate("loginWindow", "用户名/邮箱/手机"))
        self.label_2.setText(_translate("loginWindow", "密码"))
        self.pushButtonLogin.setText(_translate("loginWindow", "登陆"))
        self.pushButtonRegister.setText(_translate("loginWindow", "没有codia账户？请点击这里注册"))
        self.pushButtonReset.setText(_translate("loginWindow", "忘记密码"))
        self.checkBox.setText(_translate("loginWindow", "记住密码"))
        self.menu.setTitle(_translate("loginWindow", "帮助"))
        self.actions.setText(_translate("loginWindow", "s"))
        self.action.setText(_translate("loginWindow", "关于"))
        self.actionsd.setText(_translate("loginWindow", "登陆"))
        self.action_2.setText(_translate("loginWindow", "关于"))
