# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registerWindow(object):
    def setupUi(self, registerWindow):
        registerWindow.setObjectName("registerWindow")
        registerWindow.resize(721, 334)
        registerWindow.setMaximumSize(QtCore.QSize(721, 334))
        self.label = QtWidgets.QLabel(registerWindow)
        self.label.setGeometry(QtCore.QRect(115, 81, 146, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(registerWindow)
        self.label_2.setGeometry(QtCore.QRect(130, 110, 120, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(registerWindow)
        self.label_3.setGeometry(QtCore.QRect(170, 140, 80, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(registerWindow)
        self.label_4.setGeometry(QtCore.QRect(170, 170, 80, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_userphone = QtWidgets.QLineEdit(registerWindow)
        self.lineEdit_userphone.setGeometry(QtCore.QRect(290, 80, 261, 21))
        self.lineEdit_userphone.setObjectName("lineEdit_userphone")
        self.lineEdit_username = QtWidgets.QLineEdit(registerWindow)
        self.lineEdit_username.setGeometry(QtCore.QRect(290, 110, 261, 21))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(registerWindow)
        self.lineEdit_password.setGeometry(QtCore.QRect(290, 140, 261, 21))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lineEdit_checkpassword = QtWidgets.QLineEdit(registerWindow)
        self.lineEdit_checkpassword.setGeometry(QtCore.QRect(290, 170, 261, 21))
        self.lineEdit_checkpassword.setObjectName("lineEdit_checkpassword")
        self.pushButton = QtWidgets.QPushButton(registerWindow)
        self.pushButton.setGeometry(QtCore.QRect(260, 210, 191, 32))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(registerWindow)
        QtCore.QMetaObject.connectSlotsByName(registerWindow)

    def retranslateUi(self, registerWindow):
        _translate = QtCore.QCoreApplication.translate
        registerWindow.setWindowTitle(_translate("registerWindow", "注册"))
        self.label.setText(_translate("registerWindow", "请输入你的邮箱或手机："))
        self.label_2.setText(_translate("registerWindow", "请输入你的用户名："))
        self.label_3.setText(_translate("registerWindow", "请输入密码："))
        self.label_4.setText(_translate("registerWindow", "请确认密码："))
        self.pushButton.setText(_translate("registerWindow", "注册"))
