# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResetPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResetPassword(object):
    def setupUi(self, ResetPassword):
        ResetPassword.setObjectName("ResetPassword")
        ResetPassword.resize(653, 300)
        ResetPassword.setMaximumSize(QtCore.QSize(653, 300))
        self.label = QtWidgets.QLabel(ResetPassword)
        self.label.setGeometry(QtCore.QRect(50, 60, 181, 51))
        self.label.setObjectName("label")
        self.alineEdit_Account = QtWidgets.QLineEdit(ResetPassword)
        self.alineEdit_Account.setGeometry(QtCore.QRect(250, 70, 231, 21))
        self.alineEdit_Account.setObjectName("alineEdit_Account")
        self.pushButtonGetCheck = QtWidgets.QPushButton(ResetPassword)
        self.pushButtonGetCheck.setGeometry(QtCore.QRect(510, 70, 113, 32))
        self.pushButtonGetCheck.setObjectName("pushButtonGetCheck")
        self.label_2 = QtWidgets.QLabel(ResetPassword)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 141, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_CheckNum = QtWidgets.QLineEdit(ResetPassword)
        self.lineEdit_CheckNum.setGeometry(QtCore.QRect(250, 130, 231, 21))
        self.lineEdit_CheckNum.setObjectName("lineEdit_CheckNum")
        self.label_3 = QtWidgets.QLabel(ResetPassword)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ResetPassword)
        self.label_4.setGeometry(QtCore.QRect(50, 190, 81, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_NewPassword = QtWidgets.QLineEdit(ResetPassword)
        self.lineEdit_NewPassword.setGeometry(QtCore.QRect(250, 160, 231, 21))
        self.lineEdit_NewPassword.setObjectName("lineEdit_NewPassword")
        self.lineEdit_Check_NewPassword = QtWidgets.QLineEdit(ResetPassword)
        self.lineEdit_Check_NewPassword.setGeometry(QtCore.QRect(250, 190, 231, 21))
        self.lineEdit_Check_NewPassword.setObjectName("lineEdit_Check_NewPassword")
        self.pushButton_OK = QtWidgets.QPushButton(ResetPassword)
        self.pushButton_OK.setGeometry(QtCore.QRect(290, 230, 161, 31))
        self.pushButton_OK.setObjectName("pushButton_OK")

        self.retranslateUi(ResetPassword)
        QtCore.QMetaObject.connectSlotsByName(ResetPassword)

    def retranslateUi(self, ResetPassword):
        _translate = QtCore.QCoreApplication.translate
        ResetPassword.setWindowTitle(_translate("ResetPassword", "重置密码"))
        self.label.setText(_translate("ResetPassword", "<html><head/><body><p>请输入你需要重置密码账号</p><p>绑定的邮箱或手机号</p></body></html>"))
        self.pushButtonGetCheck.setText(_translate("ResetPassword", "获取验证码"))
        self.label_2.setText(_translate("ResetPassword", "请输入验证码"))
        self.label_3.setText(_translate("ResetPassword", "请输入新密码"))
        self.label_4.setText(_translate("ResetPassword", "验证新密码"))
        self.pushButton_OK.setText(_translate("ResetPassword", "确定"))
